import tailwindcss from '@tailwindcss/vite';
import vue from '@vitejs/plugin-vue';
import vike from 'vike/plugin';
import { defineConfig } from 'vite';

export default defineConfig({
  // Served from GitHub Pages under /gerrymander-solver/.
  base: '/gerrymander-solver/',
  plugins: [
    vike(),
    vue({
      include: [ /\.vue$/ ],
    }),
    tailwindcss(),
  ],
  server: {
    // The gerrymandle.com API sends no CORS headers; proxy it in dev so the
    // browser can fetch /api/* same-origin. Production uses puzzles.json
    // generated by scripts/fetch-puzzles.mjs (postbuild).
    proxy: {
      '/api': 'https://gerrymandle.com',
    },
  },
});
